export const AI_CONFIG = {
  enabled: true,
  default_provider: '',
  active_provider: '',
  model: '',
  embedding_model: '@cf/baai/bge-small-en-v1.5',
  // Active providers that the system can use. 
  // All active providers are initialized in parallel.
  active_providers: [], 
  temperature: 0.7,
  max_tokens: 2048,
  rag_enabled: true,
  agent_personality: 'professional',
  preferred_model: '',
  help_provider: 'cloudflare',
  help_model: '@cf/meta/llama-3.1-8b-instruct',
  changelog_provider: 'cloudflare',
  changelog_model: '@cf/meta/llama-3.1-8b-instruct',
  chat_provider: '',
  chat_model: '',
  translation_model: '@cf/meta/m2m100-1.2b',
  vision_model: '',
  transcription_model: '@cf/openai/whisper',
  providers: {
    gemini: {
      name: 'Google Gemini',
      apiKeyEnvVar: 'GEMINI_API_KEY',
      baseUrl: 'https://generativelanguage.googleapis.com/v1beta/models/{{model}}:generateContent',
      defaultModel: '',
      type: 'google-v1beta',
      color: 'bg-indigo-500 text-white',
      icon: 'Brain',
      iconColor: 'text-indigo-500',
      typeName: 'Gemini',
    },
    openai: {
      name: 'OpenAI',
      apiKeyEnvVar: 'OPENAI_API_KEY',
      baseUrl: 'https://api.openai.com/v1/chat/completions',
      defaultModel: '',
      type: 'openai-v1',
      color: 'bg-emerald-600 text-white',
      icon: 'Sparkles',
      iconColor: 'text-emerald-500',
      typeName: 'OpenAI',
    },
    anthropic: {
      name: 'Anthropic Claude',
      apiKeyEnvVar: 'ANTHROPIC_API_KEY',
      baseUrl: 'https://api.anthropic.com/v1/messages',
      defaultModel: '',
      type: 'anthropic-v1',
      color: 'bg-orange-600 text-white',
      icon: 'Zap',
      iconColor: 'text-orange-600',
      typeName: 'Claude',
    },
    cloudflare: {
      name: 'Cloudflare Workers AI',
      apiKeyEnvVar: 'CLOUDFLARE_API_TOKEN',
      accountId: '',
      baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{{accountId}}/ai/run/{{model}}',
      defaultModel: '',
      type: 'cloudflare-rpc',
      color: 'bg-orange-500 text-white',
      icon: 'Zap',
      iconColor: 'text-amber-500',
      typeName: 'Workers AI',
    },
    github: {
      name: 'GitHub Copilot / Models',
      apiKeyEnvVar: 'GITHUB_TOKEN',
      baseUrl: 'https://models.inference.ai.azure.com/chat/completions',
      defaultModel: '',
      type: 'github-v1',
      color: 'bg-slate-800 text-white',
      icon: 'Github',
      iconColor: 'text-slate-800',
      typeName: 'GitHub',
    },
    groq: {
      name: 'Groq Cloud',
      apiKeyEnvVar: 'GROQ_API_KEY',
      baseUrl: 'https://api.groq.com/openai/v1/chat/completions',
      defaultModel: '',
      type: 'openai-v1',
      color: 'bg-rose-600 text-white',
      icon: 'Zap',
      iconColor: 'text-rose-600',
      typeName: 'Groq',
    },
    deepseek: {
      name: 'DeepSeek',
      apiKeyEnvVar: 'DEEPSEEK_API_KEY',
      baseUrl: 'https://api.deepseek.com/chat/completions',
      defaultModel: '',
      type: 'openai-v1',
      color: 'bg-blue-700 text-white',
      icon: 'Cpu',
      iconColor: 'text-blue-700',
      typeName: 'DeepSeek',
    },
  },
  // Dynamic Model Registry - Baseline contains only essential bootstrap models
  // The system will automatically expand this list via the "AI Inventory" and DB overrides (D1)
  models: [ 
    { id: "@cf/meta/llama-3.1-8b-instruct", name: "Llama 3.1 8B (Direct)", provider: 'cloudflare', capabilities: ['chat', 'fast'], contextWindow: 131072, enabled: true },
    { id: "gpt-4o-mini", name: "GPT-4o Mini", provider: 'openai', capabilities: ['chat', 'fast'], contextWindow: 128000, enabled: true },
    { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash", provider: 'gemini', capabilities: ['chat', 'fast', 'vision'], contextWindow: 1000000, enabled: true },
    { id: "claude-3-5-sonnet-20240620", name: "Claude 3.5 Sonnet", provider: 'anthropic', capabilities: ['chat', 'vision'], contextWindow: 200000, enabled: true }
  ],
  requestConfig: {
    timeout: 30000,
    retries: 3,
    retryDelay: 1000,
  },
} as any;
